import type { LevelConfig } from '../types';

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    production: 'Cop Show Pilot',
    height: 20,
    targetType: 'airbag',
    targetSize: 55,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: true,
    pay: 500,
    coordinatorLine: "Easy day, kid. Short fall, huge pad. Just don't overthink it.",
  },
  {
    level: 2,
    production: 'Mall Cop 4',
    height: 25,
    targetType: 'airbag',
    targetSize: 45,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: true,
    pay: 750,
    coordinatorLine: "Little higher, still a big bag. Trust it. Flat on your back.",
  },
  {
    level: 3,
    production: 'Action Hour Ep. 3',
    height: 20,
    targetType: 'boxes',
    targetSize: 40,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: true,
    pay: 1000,
    coordinatorLine: "Boxes this time. Short fall. Same idea — flat on your back.",
  },
  {
    level: 4,
    production: 'Lethal Fury 2',
    height: 30,
    targetType: 'airbag',
    targetSize: 40,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: false,
    pay: 1500,
    coordinatorLine: "No more training wheels. 30 feet. You know the drill.",
  },
  {
    level: 5,
    production: 'Brooklyn Beat',
    height: 35,
    targetType: 'boxes',
    targetSize: 28,
    idealAngle: 90,
    wind: 3,
    windGust: 1,
    showTimingHints: false,
    pay: 2000,
    coordinatorLine: "We need a 35-foot fall off the parking garage. Bag's offset to the left. Watch your drift.",
  },
  {
    level: 6,
    production: 'Skyscraper',
    height: 40,
    targetType: 'airbag',
    targetSize: 26,
    idealAngle: 90,
    wind: -4,
    windGust: 1,
    showTimingHints: false,
    pay: 2500,
    coordinatorLine: "40 feet. Wind's picking up from the east. Compensate on your way down.",
  },
  {
    level: 7,
    production: 'Prison Break S2',
    height: 45,
    targetType: 'boxes',
    targetSize: 24,
    idealAngle: 90,
    wind: 5,
    windGust: 2,
    showTimingHints: false,
    pay: 3000,
    coordinatorLine: "Boxes are tight on this one. Wind's real. Stay sharp.",
  },
  {
    level: 8,
    production: 'Die Tough',
    height: 55,
    targetType: 'airbag',
    targetSize: 26,
    idealAngle: 90,
    wind: -5,
    windGust: 2,
    showTimingHints: false,
    pay: 4000,
    coordinatorLine: "55 feet into a medium bag. Wind's moderate. I need you sharp.",
  },
  {
    level: 9,
    production: 'Night Shift',
    height: 60,
    targetType: 'airbag',
    targetSize: 22,
    idealAngle: 90,
    wind: -6,
    windGust: 2,
    showTimingHints: false,
    pay: 5000,
    coordinatorLine: "60 feet. Bag's offset and the wind is unpredictable. Focus.",
  },
  {
    level: 10,
    production: 'Rooftop Chase',
    height: 70,
    targetType: 'airbag',
    targetSize: 20,
    idealAngle: 90,
    wind: 6,
    windGust: 2,
    showTimingHints: false,
    pay: 6000,
    coordinatorLine: "70 feet into a small bag. Wind is strong. This is where the pros separate.",
  },
  {
    level: 11,
    production: 'The Enforcer',
    height: 80,
    targetType: 'boxes',
    targetSize: 18,
    idealAngle: 90,
    wind: 5,
    windGust: 2,
    showTimingHints: false,
    pay: 7000,
    coordinatorLine: "80 feet into a narrow box stack. Precision landing. No room for error.",
  },
  {
    level: 12,
    production: 'Harbor Patrol',
    height: 50,
    targetType: 'water',
    targetSize: 30,
    idealAngle: 0,
    wind: 4,
    windGust: 1,
    showTimingHints: false,
    pay: 6500,
    coordinatorLine: "Water gag. 50 feet. Go in feet first or you're gonna have a bad day.",
  },
  {
    level: 13,
    production: 'Bridge & Tunnel',
    height: 80,
    targetType: 'water',
    targetSize: 25,
    idealAngle: 0,
    wind: 7,
    windGust: 2,
    showTimingHints: false,
    pay: 8000,
    coordinatorLine: "80 feet off the bridge into the river. Wind plus feet first. Good luck.",
  },
  {
    level: 14,
    production: 'Tower Inferno 2',
    height: 100,
    targetType: 'airbag',
    targetSize: 18,
    idealAngle: 90,
    wind: 6,
    windGust: 2,
    showTimingHints: false,
    pay: 10000,
    coordinatorLine: "Triple digits. 100 feet into a small bag. There'll be fire VFX. Don't flinch.",
  },
  {
    level: 15,
    production: 'Dam Buster',
    height: 100,
    targetType: 'water',
    targetSize: 24,
    idealAngle: 0,
    wind: -7,
    windGust: 3,
    showTimingHints: false,
    pay: 10000,
    coordinatorLine: "100 feet into the reservoir. Wind is nasty. Feet first. Period.",
  },
  {
    level: 16,
    production: 'Cliffhanger',
    height: 120,
    targetType: 'airbag',
    targetSize: 16,
    idealAngle: 90,
    wind: -8,
    windGust: 3,
    showTimingHints: false,
    pay: 12000,
    coordinatorLine: "120 feet. Small bag, offset, strong wind. This is not for amateurs.",
  },
  {
    level: 17,
    production: 'The Fall Guy (TV)',
    height: 130,
    targetType: 'boxes',
    targetSize: 14,
    idealAngle: 90,
    wind: 7,
    windGust: 2,
    showTimingHints: false,
    pay: 13000,
    coordinatorLine: "130 feet into a tiny box stack. Precision required. Earn that paycheck.",
  },
  {
    level: 18,
    production: 'Chopper Down',
    height: 150,
    targetType: 'water',
    targetSize: 18,
    idealAngle: 0,
    wind: 8,
    windGust: 3,
    showTimingHints: false,
    pay: 15000,
    coordinatorLine: "Helicopter at 150 feet. Small water zone. Wind is extreme. Godspeed.",
  },
  {
    level: 19,
    production: 'Canyon Jump',
    height: 170,
    targetType: 'airbag',
    targetSize: 14,
    idealAngle: 90,
    wind: -8,
    windGust: 3,
    showTimingHints: false,
    pay: 18000,
    coordinatorLine: "170 feet. Tiny bag. Extreme wind. Only legends attempt this.",
  },
  {
    level: 20,
    production: "The Legend's Last Gag",
    height: 200,
    targetType: 'airbag',
    targetSize: 12,
    idealAngle: 90,
    wind: 8,
    windGust: 3,
    showTimingHints: false,
    pay: 25000,
    coordinatorLine: "Alright legend, this is the big one. 200 feet. Bag is... well, you'll see.",
  },
];

export function getLevel(levelNum: number): LevelConfig {
  const idx = Math.min(levelNum - 1, LEVELS.length - 1);
  return LEVELS[Math.max(0, idx)];
}
