import type { LevelConfig } from '../types';

export const LEVELS: LevelConfig[] = [
  {
    level: 1,
    production: 'Cop Show Pilot',
    height: 20,
    targetType: 'airbag',
    targetSize: 55,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: true,
    pay: 500,
    coordinatorLine: "Easy day, kid. Short fall, huge pad. Just don't overthink it.",
  },
  {
    level: 2,
    production: 'Mall Cop 4',
    height: 25,
    targetType: 'airbag',
    targetSize: 45,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: true,
    pay: 750,
    coordinatorLine: "Little higher, still a big bag. Trust it. Flat on your back.",
  },
  {
    level: 3,
    production: 'Action Hour Ep. 3',
    height: 20,
    targetType: 'boxes',
    targetSize: 40,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: true,
    pay: 1000,
    coordinatorLine: "Boxes this time. Short fall. Same idea — flat on your back.",
  },
  {
    level: 4,
    production: 'Lethal Fury 2',
    height: 30,
    targetType: 'airbag',
    targetSize: 40,
    idealAngle: 90,
    wind: 0,
    windGust: 0,
    showTimingHints: false,
    pay: 1500,
    coordinatorLine: "No more training wheels. 30 feet. You know the drill.",
  },
  {
    level: 5,
    production: 'Brooklyn Beat',
    height: 35,
    targetType: 'boxes',
    targetSize: 28,
    idealAngle: 90,
    wind: 3,
    windGust: 1,
    showTimingHints: false,
    pay: 2000,
    coordinatorLine: "We need a 35-foot fall off the parking garage. Bag's offset to the left. Watch your drift.",
  },
  {
    level: 6,
    production: 'Skyscraper',
    height: 40,
    targetType: 'airbag',
    targetSize: 26,
    idealAngle: 90,
    wind: -4,
    windGust: 1,
    showTimingHints: false,
    pay: 2500,
    coordinatorLine: "40 feet. Wind's picking up from the east. Compensate on your way down.",
  },
  {
    level: 7,
    production: 'Prison Break S2',
    height: 45,
    targetType: 'boxes',
    targetSize: 24,
    idealAngle: 90,
    wind: 5,
    windGust: 2,
    showTimingHints: false,
    pay: 3000,
    coordinatorLine: "Boxes are tight on this one. Wind's real. Stay sharp.",
  },
  {
    level: 8,
    production: 'Die Tough',
    height: 55,
    targetType: 'airbag',
    targetSize: 26,
    idealAngle: 90,
    wind: -5,
    windGust: 2,
    showTimingHints: false,
    pay: 4000,
    coordinatorLine: "55 feet into a medium bag. Wind's moderate. I need you sharp.",
  },
  {
    level: 9,
    production: 'Night Shift',
    height: 60,
    targetType: 'airbag',
    targetSize: 22,
    idealAngle: 90,
    wind: -6,
    windGust: 2,
    showTimingHints: false,
    pay: 5000,
    coordinatorLine: "60 feet. Bag's offset and the wind is unpredictable. Focus.",
  },
  {
    level: 10,
    production: 'Rooftop Chase',
    height: 70,
    targetType: 'airbag',
    targetSize: 20,
    idealAngle: 90,
    wind: 6,
    windGust: 2,
    showTimingHints: false,
    pay: 6000,
    coordinatorLine: "70 feet into a small bag. Wind is strong. This is where the pros separate.",
  },
  {
    level: 11,
    production: 'The Enforcer',
    height: 80,
    targetType: 'boxes',
    targetSize: 18,
    idealAngle: 90,
    wind: 5,
    windGust: 2,
    showTimingHints: false,
    pay: 7000,
    coordinatorLine: "80 feet into a narrow box stack. Precision landing. No room for error.",
  },
  {
    level: 12,
    production: 'Harbor Patrol',
    height: 50,
    targetType: 'water',
    targetSize: 30,
    idealAngle: 0,
    wind: 4,
    windGust: 1,
    showTimingHints: false,
    pay: 6500,
    coordinatorLine: "Water gag. 50 feet. Go in feet first or you're gonna have a bad day.",
  },
  {
    level: 13,
    production: 'Bridge & Tunnel',
    height: 80,
    targetType: 'water',
    targetSize: 25,
    idealAngle: 0,
    wind: 7,
    windGust: 2,
    showTimingHints: false,
    pay: 8000,
    coordinatorLine: "80 feet off the bridge into the river. Wind plus feet first. Good luck.",
  },
  {
    level: 14,
    production: 'Tower Inferno 2',
    height: 100,
    targetType: 'airbag',
    targetSize: 18,
    idealAngle: 90,
    wind: 6,
    windGust: 2,
    showTimingHints: false,
    pay: 10000,
    coordinatorLine: "Triple digits. 100 feet into a small bag. There'll be fire VFX. Don't flinch.",
  },
  {
    level: 15,
    production: 'Dam Buster',
    height: 100,
    targetType: 'water',
    targetSize: 24,
    idealAngle: 0,
    wind: -7,
    windGust: 3,
    showTimingHints: false,
    pay: 10000,
    coordinatorLine: "100 feet into the reservoir. Wind is nasty. Feet first. Period.",
  },
  {
    level: 16,
    production: 'Cliffhanger',
    height: 120,
    targetType: 'airbag',
    targetSize: 16,
    idealAngle: 90,
    wind: -8,
    windGust: 3,
    showTimingHints: false,
    pay: 12000,
    coordinatorLine: "120 feet. Small bag, offset, strong wind. This is not for amateurs.",
  },
  {
    level: 17,
    production: 'The Fall Guy (TV)',
    height: 130,
    targetType: 'boxes',
    targetSize: 14,
    idealAngle: 90,
    wind: 7,
    windGust: 2,
    showTimingHints: false,
    pay: 13000,
    coordinatorLine: "130 feet into a tiny box stack. Precision required. Earn that paycheck.",
  },
  {
    level: 18,
    production: 'Chopper Down',
    height: 150,
    targetType: 'water',
    targetSize: 18,
    idealAngle: 0,
    wind: 8,
    windGust: 3,
    showTimingHints: false,
    pay: 15000,
    coordinatorLine: "Helicopter at 150 feet. Small water zone. Wind is extreme. Godspeed.",
  },
  {
    level: 19,
    production: 'Canyon Jump',
    height: 170,
    targetType: 'airbag',
    targetSize: 14,
    idealAngle: 90,
    wind: -8,
    windGust: 3,
    showTimingHints: false,
    pay: 18000,
    coordinatorLine: "170 feet. Tiny bag. Extreme wind. Only legends attempt this.",
  },
  {
    level: 20,
    production: "The Legend's Last Gag",
    height: 200,
    targetType: 'airbag',
    targetSize: 12,
    idealAngle: 90,
    wind: 8,
    windGust: 3,
    showTimingHints: false,
    pay: 25000,
    coordinatorLine: "Alright legend, this is the big one. 200 feet. Bag is... well, you'll see.",
  },
  // --- LEVELS 21-40: Helicopter & Hot Air Balloon jumps ---
  {
    level: 21, production: 'Chopper One', height: 60, targetType: 'airbag', targetSize: 40,
    idealAngle: 90, wind: 3, windGust: 1, showTimingHints: false, pay: 7000, jumpType: 'helicopter',
    coordinatorLine: "First helicopter gag. 60 feet, nice big bag. The chopper's stable. Just let go.",
  },
  {
    level: 22, production: 'Warehouse Siege', height: 90, targetType: 'boxes', targetSize: 22,
    idealAngle: 90, wind: -5, windGust: 2, showTimingHints: false, pay: 8000,
    coordinatorLine: "90 feet off the warehouse. Boxes are tight. Wind's from the east.",
  },
  {
    level: 23, production: 'Around The World', height: 70, targetType: 'water', targetSize: 30,
    idealAngle: 0, wind: 4, windGust: 1, showTimingHints: false, pay: 7500, jumpType: 'balloon',
    coordinatorLine: "Balloon jump over the lake. 70 feet. Go in feet first. The basket swings a little.",
  },
  {
    level: 24, production: 'Air Rescue', height: 100, targetType: 'airbag', targetSize: 24,
    idealAngle: 90, wind: 6, windGust: 2, showTimingHints: false, pay: 9000, jumpType: 'helicopter',
    coordinatorLine: "100 feet from the chopper. Wind is real up there. Bag's offset. Watch it.",
  },
  {
    level: 25, production: 'Steel City', height: 110, targetType: 'boxes', targetSize: 18,
    idealAngle: 90, wind: 7, windGust: 2, showTimingHints: false, pay: 9500,
    coordinatorLine: "110-foot building. Narrow box stack. Heavy crosswind. Welcome to the big leagues.",
  },
  {
    level: 26, production: 'Sky Pirates', height: 120, targetType: 'water', targetSize: 22,
    idealAngle: 0, wind: -6, windGust: 2, showTimingHints: false, pay: 11000, jumpType: 'balloon',
    coordinatorLine: "120 feet from the balloon into the ocean. Feet first or it'll feel like concrete.",
  },
  {
    level: 27, production: 'Black Hawk Sunset', height: 130, targetType: 'airbag', targetSize: 18,
    idealAngle: 90, wind: 7, windGust: 2, showTimingHints: false, pay: 13000, jumpType: 'helicopter',
    coordinatorLine: "130 feet from the Huey. Small bag, strong wind. The downdraft is real.",
  },
  {
    level: 28, production: 'Condemned', height: 140, targetType: 'boxes', targetSize: 14,
    idealAngle: 90, wind: -8, windGust: 3, showTimingHints: false, pay: 14000,
    coordinatorLine: "140-foot condemned building. Tiny box stack. Extreme wind. Don't look down.",
  },
  {
    level: 29, production: 'Balloon Voyage', height: 150, targetType: 'water', targetSize: 20,
    idealAngle: 0, wind: 6, windGust: 2, showTimingHints: false, pay: 15000, jumpType: 'balloon',
    coordinatorLine: "150 feet from the balloon. Small water zone. Wind's moderate. Commit to it.",
  },
  {
    level: 30, production: 'Extraction Point', height: 160, targetType: 'airbag', targetSize: 14,
    idealAngle: 90, wind: -8, windGust: 3, showTimingHints: false, pay: 16000, jumpType: 'helicopter',
    coordinatorLine: "160 feet from the chopper. Tiny bag. Rotor wash is murder. Aim true.",
  },
  {
    level: 31, production: 'Tower of Glass', height: 170, targetType: 'boxes', targetSize: 12,
    idealAngle: 90, wind: 8, windGust: 3, showTimingHints: false, pay: 18000,
    coordinatorLine: "170 feet. Smallest box stack you've ever seen. If you can see it from up there.",
  },
  {
    level: 32, production: 'Stratosphere', height: 180, targetType: 'water', targetSize: 18,
    idealAngle: 0, wind: -9, windGust: 3, showTimingHints: false, pay: 19000, jumpType: 'balloon',
    coordinatorLine: "180 feet from the balloon. Narrow water target. Wind is vicious. Feet. First.",
  },
  {
    level: 33, production: 'Valor', height: 200, targetType: 'airbag', targetSize: 14,
    idealAngle: 90, wind: 9, windGust: 3, showTimingHints: false, pay: 22000, jumpType: 'helicopter',
    coordinatorLine: "200 feet from the helicopter. Small bag. You've done this before. Just... higher.",
  },
  {
    level: 34, production: 'Final Floor', height: 210, targetType: 'boxes', targetSize: 12,
    idealAngle: 90, wind: -9, windGust: 3, showTimingHints: false, pay: 24000,
    coordinatorLine: "210-foot skyscraper. Boxes the size of a phone booth. Extreme wind. You sure?",
  },
  {
    level: 35, production: 'Cloudbreak', height: 220, targetType: 'water', targetSize: 16,
    idealAngle: 0, wind: 9, windGust: 3, showTimingHints: false, pay: 25000, jumpType: 'balloon',
    coordinatorLine: "220 feet from the balloon into a narrow channel. Wind is extreme.",
  },
  {
    level: 36, production: 'Apex', height: 240, targetType: 'airbag', targetSize: 12,
    idealAngle: 90, wind: -10, windGust: 3, showTimingHints: false, pay: 28000, jumpType: 'helicopter',
    coordinatorLine: "240 feet. Tiny bag. Hurricane-force wind. Only one person has ever done this.",
  },
  {
    level: 37, production: 'Condemned II', height: 250, targetType: 'boxes', targetSize: 10,
    idealAngle: 90, wind: 10, windGust: 3, showTimingHints: false, pay: 30000,
    coordinatorLine: "250 feet. The box stack is barely there. If you miss, there is no second take.",
  },
  {
    level: 38, production: 'Into The Deep', height: 260, targetType: 'water', targetSize: 14,
    idealAngle: 0, wind: -10, windGust: 4, showTimingHints: false, pay: 32000, jumpType: 'balloon',
    coordinatorLine: "260 feet. Narrow water. Gusts are unpredictable. This is not sane.",
  },
  {
    level: 39, production: 'Terminal Velocity', height: 280, targetType: 'airbag', targetSize: 10,
    idealAngle: 90, wind: 10, windGust: 4, showTimingHints: false, pay: 35000, jumpType: 'helicopter',
    coordinatorLine: "280 feet from the chopper. The bag looks like a postage stamp. Terminal velocity.",
  },
  {
    level: 40, production: 'The Immortal Gag', height: 300, targetType: 'airbag', targetSize: 10,
    idealAngle: 90, wind: -10, windGust: 4, showTimingHints: false, pay: 50000, jumpType: 'balloon',
    coordinatorLine: "300 feet from a balloon. Postage-stamp bag. Gale-force wind. If you survive, you're a god.",
  },
];

export function getLevel(levelNum: number): LevelConfig {
  const idx = Math.min(levelNum - 1, LEVELS.length - 1);
  return LEVELS[Math.max(0, idx)];
}
